### PR TITLE
Added load UTF-8 + added key verif

### PR DESCRIPTION
**Pull request by R-D-Y**
- Added encoding='utf-8
- Try  key word_time_map 
- Renamed by default output name on AWS Transcribe

### CODE REVIEW

**Comment by jesse-ashmore** [comment]
Thanks, but this looks like an automated PR (particularly due to the removal of all the comments).

If it's not an automated PR, why remove all the comments? Also, I don't think we really need to verify keys here since data is built up from the Transcribe output anyways.

FYI, I'll close this PR in a while if no reply.

**Comment by R-D-Y** [comment]
Hi, sorry i made a mistake, the key was a personnal test for me, my only addons was the utf-8 enconding.

**Comment by jesse-ashmore** [comment]
Thanks for the clarification. Could you reduce the diff to just the utf-8 encoding then? (also please add back the comments lol)

**Comment by R-D-Y** [comment]
sure !

**Comment by R-D-Y** [comment]
https://github.com/JeeZeh/winston/pull/2

**Pull request closed without merging**
